calendars:
  - source: "ESPN"
    type: espn
  - url: https://downtowncarypark.com/wp-json/nmc-feeds/v1/events
    source: "Downtown Cary Park"
    type: nmc_json
  - url: https://www.visitraleigh.com/event/rss/
    source: "Visit Raleigh"
    type: rss
  - url: https://www.apexnc.org/RSSFeed.aspx?ModID=58&CID=All-calendar.xml
    source: "Town of Apex"
    type: rss
  - url: https://www.carync.gov/connect-engage/calendar
    source: "Town of Cary"
    type: html
