apiVersion: v2
name: local-pulse
description: Local Pulse - aggregates local events from multiple websites
type: application
version: 0.2.0
appVersion: "1.0.0"
keywords:
  - events
  - calendar
  - aggregation
maintainers: []
